version: '2'
services:
  Balancer:
    image: "debian:stable"
    environment:
      HOSTS: ${HOSTS}
      HCLOUD_TOKEN: ${HCLOUD_TOKEN}
      PRIVATE_KEY: |-
        ${PRIVATKEY}
      PUBLIC_KEY: |-
        ${PUBLICKEY}
      HOSTS: ${HOSTS}
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environmentAdmin,agent
