name: Fire(wall) extinguisher
description: |
  Logs into target hosts and allows firewall access to the rancher droplets
verison: 0.1.0
category: Storage
labels:
  io.rancher.orchestration.supported: 'cattle'
