name: Hetzner Cloud Loadbalancer
description: |
  Create 2 hosts in hetzner cloud sharing a floating ip to do high availaibility load balancing
version: 0.2.0
category: Loadbalancer
labels:
  io.rancher.orchestration.supported: 'cattle'
