version: '2'
catalog:
  name: Fire fence
  version: 0.1.0
  description: Use iptables to firewall off a list of ports
  minimum_rancher_version: 1.6.0
  questions:
    - variable: PORT
      label: Port to Firewall
      # The description of the question to show the user how to answer the question.
      description: | 
        The port which will be firewalled on the ohsts
      default: 111
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected
    - variable: ALLOWED_ADDRESSES
      label: Allowed Addresses
      # The description of the question to show the user how to answer the question.
      description: | 
        Addresse allowed to access the port
      required: true # (Optional) Whether or not an answer is required. By default, it's considered `false`.
      type: string # How the questions are formatted and types of response expected
services:
  Firefence:
    start_on_create: true
