version: '2'
volumes:
  {{ .Values.VOLUME }}:
    driver: ${VOLUME_DRIVER}
services:
  Balancer:
    image: "ipunktbs/hetzner-lb:1.3.0"
    restart: "no"
    environment:
      SERVERS: "${SERVERS}"
      HCLOUD_TOKEN: "${HCLOUD_TOKEN}"
      HOST_LABELS: "${HOST_LABELS}"
      FLOATING_IP: "${FLOATING_IP}"
      CLUSTER_USER_PASSWORD: "${CLUSTER_USER_PASSWORD}"
      FLOATING_IP_MONITOR_INTERVAL: "${FLOATING_IP_MONITOR_INTERVAL}"
      FLOATING_IP_MONITOR_TIMEOUT: "${FLOATING_IP_MONITOR_TIMEOUT}"
      SSH_EXTRA_PUBKEYS: |-
        ${SSH_EXTRA_PUBKEYS}
      PRIVATE_KEY: |-
        ${PRIVAT_KEY}
      PUBLIC_KEY: |-
        ${PUBLIC_KEY}
    volumes:
      - "${VOLUME}:/data${VOLUME_MOUNT_OPTIONS}"
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.start_once: true
      io.rancher.container.pull_image: always
