version: '2'
catalog:
  name: Filebeat Autodiscover
  version: 1.0.0
  description: Collects Logs for Elasticsearch
  minimum_rancher_version: 1.6.0
  questions:
    - variable: HOSTURL
      label: Host
      default: "elasticsearch:9200"
      description: |
        Your Host Adress for the Filebeat Logs
      required: true
      type: string
    - variable: PROTOCOL
      label: Protocol
      default: "http"
      description: |
        http or https
      required: true
      type: string
    - variable: ENVIRONMENT
      label: Environment
      default: "rancher"
      description: |
        Your Rancher Environment
      required: false
      type: string
    - variable: USERNAME
      label: Username
      description: |
        HTTP Auth Username
      required: false
      type: string
    - variable: PASSWORD
      label: Password
      description: |
        HTTP Auth Password
      required: false
      type: string
services:
  filebeat:
    start_on_create: true
