version: '2'
catalog:
  name: Filebeat Autodiscover
  version: 1.0.0
  description: Collects Logs for Elasticsearch
  minimum_rancher_version: 1.6.0
  questions:
    - variable: HOSTURL
      label: Host
      default: "http://elasticsearch:9200"
      description: |
        Your Host with Port for the Filebeat Logs (Adress:Port)
      required: true
      : string
    - variable: ENVIRONMENT
      label: Environment
      default: "rancher"
      description: |
        Name of your Rancher Environment your collecting Logs
      required: false
      type: string
    - variable: USERNAME
      label: Username
      default: "USER"
      description: |
        HTTP Auth Username
      required: false
      type: string
    - variable: PASSWORD
      label: Password
      description: |
        HTTP Auth Password
      required: false
      type: password
services:
  filebeat:
    start_on_create: true
