name: Fire fence
description: |
  Use iptables to firewall off a list of ports for all hosts, only allowing access from specified ips
version: 0.1.0
category: Firewall
maintainer: Sven Speckmaier
license: MIT
projectURL: https://github.com/ipunkt/docker-firewall-port
